spring:
    datasource:
       url: jdbc:mysql://localhost/vote_test
       username: root
       password: root
    thymeleaf:
        cache: false
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect